# Generated by Django 4.2 on 2026-05-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_brand_description_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 10, 16, 2, 18, 516107, tzinfo=datetime.timezone.utc), verbose_name='Fecha Caducidad'),
        ),
    ]
